apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-hpa-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auto-hpa-controller
rules:
- apiGroups: [""]
  resources: ["namespaces", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling/v2"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auto-hpa-controller
subjects:
- kind: ServiceAccount
  name: auto-hpa-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: auto-hpa-controller
  apiGroup: rbac.authorization.k8s.io
